### ISSUE TITLE
Update README configuration section

### ISSUE THREAD

**Issue by yk-sgr** [Votebot/voteBot#11]
Update the README with the matching values of [ConfigCatConfig](https://github.com/Votebot/voteBot/blob/master/src/main/kotlin/wtf/votebot/bot/config/ConfigCatConfig.kt) and [EnvConfig](https://github.com/Votebot/voteBot/blob/master/src/main/kotlin/wtf/votebot/bot/config/EnvConfig.kt)

**Comment by DRSchlaubi** [comment]
@Seliba You're to lazy here is a task for you

**Comment by yk-sgr** [comment]
Agreed
