### ISSUE TITLE
double printing votes, closing not working. 

### ISSUE THREAD

**Issue by T3sT3ro** [Votebot/voteBot#14]
![image](https://user-images.githubusercontent.com/5300963/64196523-547d1800-ce84-11e9-83e6-3da465e4f4a7.png)

**Comment by DRSchlaubi** [comment]
Looks like the bot runs twice let me quickly check that

**Comment by DRSchlaubi** [comment]
Okay, both the double printing and the close issue should be fixed now.
The docker container, in which the bot was running, didn't support fonts so it couldn't generate the PieChart. Could you please confirm that it works for you now @T3sT3ro ?

**Comment by T3sT3ro** [comment]
@DRSchlaubi Seems ok to me now.
