### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by yk-sgr** [Votebot/voteBot#8]
We need a CI setup for automated testing and building.
I would suggest TravisCI.

**Comment by DRSchlaubi** [comment]
What about also adding code style checks?

**Comment by yk-sgr** [comment]
Yeah, Codacy for example. But they don't need a configuration afaik.

**Comment by DRSchlaubi** [comment]
I think you can't really configure them at all

**Comment by yk-sgr** [comment]
Resolved in https://github.com/Votebot/voteBot/pull/10
